# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.SmallIntegerField(verbose_name='Line Number')),
                ('hits', models.SmallIntegerField(verbose_name='Hits')),
                ('time_consumed', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Time Consumed')),
                ('func_name', models.CharField(max_length=256, verbose_name='Function Name')),
                ('file_path', models.CharField(max_length=256, verbose_name='File Path')),
                ('file_hash', models.CharField(max_length=32, verbose_name='File Hash')),
                ('hit_at', models.DateTimeField(auto_now_add=True, verbose_name='Hit at')),
            ],
        ),
    ]
