# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
    ]
